- alias: Fingerling42
  fullName: Ivan Berman
  avatar: 'IBerman.svg'

- alias: Smehnov
  fullName: Alexander Smekhnov
  avatar: 'ASmekhnov.jpeg'

- alias: Kapitonov
  fullName: Aleksand Kapitonov
  avatar: 'Kapitonov.jpeg'

- alias: Maddhatter
  fullName: Ilya German
  avatar: 'Maddhatter.jpg'

- alias: GreatestParrot
  fullName: Arseniy Popov
  avatar: 'GreatestParrot.jpg'