name: CI

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: "16.x"

#      - name: Get yarn cache
#        id: yarn-cache
#        run: echo "::set-output name=dir::$(yarn cache dir)"

      - name: Install dependencies
#        uses: actions/cache@v1
#        with:
#          path: ${{ steps.yarn-cache.outputs.dir }}
#          key: ${{ runner.os }}-website-${{ hashFiles('**/yarn.lock') }}
#          restore-keys: |
#            ${{ runner.os }}-website-
      - run: |
          sudo npm install --global @gridsome/cli
          yarn install --frozen-lockfile 
          gridsome build
        env:
          GRIDSOME_CAPTCHAID: ${{ secrets.GRIDSOME_CAPTCHAID }}
          GRIDSOME_GS_CERTIFICATE: ${{ secrets.GRIDSOME_GS_CERTIFICATE }}
          GRIDSOME_GS_NEWS: ${{ secrets.GRIDSOME_GS_NEWS }}
          GRIDSOME_GS_REACTION: ${{ secrets.GRIDSOME_GS_REACTION }}

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist